build: fix order of tasks
fix error where specific files where not available for the build,
resulting in

```
Running "requirejs:compile" (requirejs) task
Error: ENOENT, no such file or directory
'/home/travis/build/robertkowalski/couchdb/src/fauxton/app/initialize.js'
In module tree:
    main
      app

```

how to reproduce the error, on couchdb master:

```
rm -rf share/www/ && rm -rf src/fauxton/dist && rm \
src/fauxton/app/initialize.js && make fauxton
```

it happens as `src/fauxton/app/initialize.js` is added to the
gitignore and if the file got generated before (from previous
fauxton builds) you will not run into it.